apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  HOST:  {{ .Values.configmap.data.HOST | quote }}
  VIDEOS_APP_PORT_INTERNAL: {{ .Values.configmap.data.VIDEOS_APP_PORT_INTERNAL | quote }}
  VIDEOS_APP_PORT_EXTERNAL:  {{ .Values.configmap.data.VIDEOS_APP_PORT_EXTERNAL | quote }}
  FLASK_ENV:  {{ .Values.configmap.data.FLASK_ENV | quote }}
  MONGO_HOST:  {{ .Values.configmap.data.MONGO_HOST | quote }}
  DB_NAME:  {{ .Values.configmap.data.DB_NAME | quote }}
  MONGO_PORT:  {{ .Values.configmap.data.MONGO_PORT | quote }}