apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: videos-app-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: videos-app
  endpoints:
  - port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
