apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.exposePort }}         
    targetPort: {{ .Values.deployment.container.port }}
